export const initialSet = [
  {
    id: 1234,
    name: "Rich Barr",
    email: "rb@fun.com",
    availDay: ["Monday", "Tuesday"],
    timez: "Pacific",
    ptype: ["Player", "GM"],
  },
  {
    id: 1235,
    name: "Huge Ackman",
    email: "wolvie@xman.com",
    availDay: ["Monday", "Thursday"],
    timez: "Alaskan",
    ptype: ["Player"],
  },
  {
    id: 1236,
    name: "Sarah Sammy",
    email: "sarasam@goober.com",
    availDay: ["Monday", "Friday"],
    timez: "Central",
    ptype: ["Player"],
  },
  {
    id: 1237,
    name: "Jim Bob",
    email: "jb@bj.com",
    availDay: ["Tuesday", "Wednesday"],
    timez: "Pacific",
    ptype: ["Player", "GM"],
  },
  {
    id: 1238,
    name: "Sonja Sorry",
    email: "sup@fether.com",
    availDay: ["Saturday", "Sunday"],
    timez: "Mountain",
    ptype: ["GM"],
  },
  {
    id: 1239,
    name: "Mojo Nixon",
    email: "BigFoot@redneck.com",
    availDay: ["Thursday", "Saturday"],
    timez: "Eastern",
    ptype: ["Player"],
  },
];
